module.exports = {
    apps: [
        {
            name:               "bridge-keeper-api-server",
            script:             "./app/service/gateway.js",
            watch:              false,
            ignore_watch:       ["node_modules", "logs", "report"],
            out_file:           "./logs/pm2/gateway.out.log",
            error_file:         "./logs/pm2/gateway.err.log",
            merge_logs:         true,
            max_memory_restart: "1G",
            env:                {NODE_ENV: "production"},
            exec_mode:          "fork",
            instances:          1,
            autorestart:        true,
        },
        {
            name:               "bridge-keeper-eth-core-event",
            script:             "./app/service/eth/core_event.js",
            watch:              false,
            ignore_watch:       ["node_modules", "logs", "report"],
            out_file:           "./logs/pm2/cronjob.eth.core.event.synchronizer.out.log",
            error_file:         "./logs/pm2/cronjob.eth.core.event.synchronizer.err.log",
            merge_logs:         true,
            max_memory_restart: "1G",
            env:                {NODE_ENV: "production"},
            exec_mode:          "fork",
            instances:          1,
            autorestart:        true,
        },
        {
            name:               "bridge-keeper-eth-gasprice",
            script:             "./app/service/eth/gasprice.js",
            watch:              false,
            ignore_watch:       ["node_modules", "logs", "report"],
            out_file:           "./logs/pm2/cronjob.eth.gasprice.synchronizer.out.log",
            error_file:         "./logs/pm2/cronjob.eth.gasprice.synchronizer.err.log",
            merge_logs:         true,
            max_memory_restart: "1G",
            env:                {NODE_ENV: "production"},
            exec_mode:          "fork",
            instances:          1,
            autorestart:        true,
        },
        {
            name:               "bridge-keeper-kcc-core-event",
            script:             "./app/service/kcc/core_event.js",
            watch:              false,
            ignore_watch:       ["node_modules", "logs", "report"],
            out_file:           "./logs/pm2/cronjob.kcc.core.event.synchronizer.out.log",
            error_file:         "./logs/pm2/cronjob.kcc.core.event.synchronizer.err.log",
            merge_logs:         true,
            max_memory_restart: "1G",
            env:                {NODE_ENV: "production"},
            exec_mode:          "fork",
            instances:          1,
            autorestart:        true,
        },
        {
            name:               "bridge-keeper-kcc-pair-event",
            script:             "./app/service/kcc/pair_event.js",
            watch:              false,
            ignore_watch:       ["node_modules", "logs", "report"],
            out_file:           "./logs/pm2/cronjob.kcc.pair.event.synchronizer.out.log",
            error_file:         "./logs/pm2/cronjob.kcc.pair.event.synchronizer.err.log",
            merge_logs:         true,
            max_memory_restart: "1G",
            env:                {NODE_ENV: "production"},
            exec_mode:          "fork",
            instances:          1,
            autorestart:        true,
        },
    ],
};
